- name: Install Nginx Web Server
  dnf:
    name: nginx
    state: present

- name: Создать конфигурацию NGINX из шаблона
  template:
    src: index.j2
    dest: /usr/share/nginx/html/index.html
  notify:
    - Restart Nginx

- name: Start WebServer and make it enable on boot
  service:
    name: nginx
    state: started
    enabled: yes
